name: Hexo Deploy

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      # - name: Cache NPM Dependencies
      #   uses: actions/cache@v3
      #   with:
      #     path: node_modules
      #     key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: |
      #       ${{ runner.OS }}-npm-cache-

      - name: Setup Repo
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.HEXO_DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "guyunxiang32@gmail.com"
          git config --global user.name "guyunxiang"
          git config --global init.defaultBranch main

      - name: Setup Hexo
        run: |
          npm install hexo-cli -g
          npm install

      - name: Deploy
        run: |
          hexo clean
          hexo generate
          hexo deploy